apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: flz8kyyfi-go
  janus-idp.io/tekton: flz8kyyfi-go
  backstage.io/kubernetes-id: flz8kyyfi-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: flz8kyyfi-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
